apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gitops-bootstrap
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jstrahle/gitops-demo.git
    targetRevision: main
    path: developer-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
