apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gitops-app-of-apps
  namespace: dev-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jstrahle/gitops-demo-developer.git
    targetRevision: main
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
